<?xml version="1.0" encoding="utf-8"?><Database Name="BancoSantander" Class="conexaoTOPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-77VGV2S\SQLEXPRESS;Initial Catalog=BancoSantander;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BancoSantanderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contratos" Member="Contratos">
    <Type Name="Contratos">
      <Column Name="IdContrato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Contrato" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="cpf" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="codloja" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="nomeloja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dataabertura" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="bco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="agen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>