#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoTop.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BancoSantander")]
	public partial class conexaoTOPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertContratos(Contratos instance);
    partial void UpdateContratos(Contratos instance);
    partial void DeleteContratos(Contratos instance);
    #endregion
		
		public conexaoTOPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BancoSantanderConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoTOPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoTOPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoTOPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public conexaoTOPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Contratos> Contratos
		{
			get
			{
				return this.GetTable<Contratos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contratos")]
	public partial class Contratos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdContrato;
		
		private string _Contrato;
		
		private string _Nome;
		
		private string _cpf;
		
		private string _codloja;
		
		private string _nomeloja;
		
		private System.Nullable<System.DateTime> _dataabertura;
		
		private string _bco;
		
		private string _agen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdContratoChanging(int value);
    partial void OnIdContratoChanged();
    partial void OnContratoChanging(string value);
    partial void OnContratoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OncodlojaChanging(string value);
    partial void OncodlojaChanged();
    partial void OnnomelojaChanging(string value);
    partial void OnnomelojaChanged();
    partial void OndataaberturaChanging(System.Nullable<System.DateTime> value);
    partial void OndataaberturaChanged();
    partial void OnbcoChanging(string value);
    partial void OnbcoChanged();
    partial void OnagenChanging(string value);
    partial void OnagenChanged();
    #endregion
		
		public Contratos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContrato", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdContrato
		{
			get
			{
				return this._IdContrato;
			}
			set
			{
				if ((this._IdContrato != value))
				{
					this.OnIdContratoChanging(value);
					this.SendPropertyChanging();
					this._IdContrato = value;
					this.SendPropertyChanged("IdContrato");
					this.OnIdContratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrato", DbType="VarChar(50)")]
		public string Contrato
		{
			get
			{
				return this._Contrato;
			}
			set
			{
				if ((this._Contrato != value))
				{
					this.OnContratoChanging(value);
					this.SendPropertyChanging();
					this._Contrato = value;
					this.SendPropertyChanged("Contrato");
					this.OnContratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(11)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codloja", DbType="VarChar(5)")]
		public string codloja
		{
			get
			{
				return this._codloja;
			}
			set
			{
				if ((this._codloja != value))
				{
					this.OncodlojaChanging(value);
					this.SendPropertyChanging();
					this._codloja = value;
					this.SendPropertyChanged("codloja");
					this.OncodlojaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeloja", DbType="VarChar(100)")]
		public string nomeloja
		{
			get
			{
				return this._nomeloja;
			}
			set
			{
				if ((this._nomeloja != value))
				{
					this.OnnomelojaChanging(value);
					this.SendPropertyChanging();
					this._nomeloja = value;
					this.SendPropertyChanged("nomeloja");
					this.OnnomelojaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataabertura", DbType="Date")]
		public System.Nullable<System.DateTime> dataabertura
		{
			get
			{
				return this._dataabertura;
			}
			set
			{
				if ((this._dataabertura != value))
				{
					this.OndataaberturaChanging(value);
					this.SendPropertyChanging();
					this._dataabertura = value;
					this.SendPropertyChanged("dataabertura");
					this.OndataaberturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bco", DbType="VarChar(50)")]
		public string bco
		{
			get
			{
				return this._bco;
			}
			set
			{
				if ((this._bco != value))
				{
					this.OnbcoChanging(value);
					this.SendPropertyChanging();
					this._bco = value;
					this.SendPropertyChanged("bco");
					this.OnbcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agen", DbType="VarChar(50)")]
		public string agen
		{
			get
			{
				return this._agen;
			}
			set
			{
				if ((this._agen != value))
				{
					this.OnagenChanging(value);
					this.SendPropertyChanging();
					this._agen = value;
					this.SendPropertyChanged("agen");
					this.OnagenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
